markdown:       rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments:       true
name:           PonyDevs
description:    "We ship ponies."
url:            http://ponydevs.com
permalink:      /:categories/:title
gems:
  - jekyll-redirect-from